import test from 'node:test';
import assert from 'node:assert/strict';
import {Game,score} from '../game.js';
import {createServer} from '../server.js';
const products=Array.from({length:5},(_,i)=>({id:'p'+i,name:'Produit réel test',description:'Description',images:[],priceCents:10000,source:'https://example.com',checkedAt:'2026-09-21'}));
function setup(options){const game=new Game(products,options),a=game.create('Simon'),b=game.join(a.code,'Alex');return{game,a,b,call:(s,t,d)=>game.action(s.code,s.token,t,d),view:s=>game.state(s.code,s.token)};}
test('La proximité est symétrique, plafonnée et proportionnelle au prix',()=>{assert.equal(score(10000,10000),100);assert.equal(score(9000,10000),90);assert.equal(score(11000,10000),90);assert.equal(score(100000,10000),0);assert.equal(score(0,10000),0);assert.equal(score(900,1000),90);});
test('Une partie complète, sans fuite, réponses verrouillées, égalités et revanche',()=>{const {a,b,call,view}=setup();assert.throws(()=>call(b,'start'),/hôte/);call(a,'start');for(let round=0;round<5;round++){const s=view(a);assert.equal(s.round,round);assert.equal(s.priceCents,undefined);assert.equal(s.source,undefined);assert.equal(s.product.priceCents,undefined);assert.ok(s.players.every(p=>!p.token));call(a,'guess',{round,cents:9000});assert.equal(view(b).myGuess,null);assert.equal(view(b).results,undefined);assert.throws(()=>call(a,'guess',{round,cents:10000}),/verrouillée/);call(b,'guess',{round,cents:11000});const r=view(a);assert.equal(r.phase,'reveal');assert.equal(r.priceCents,10000);assert.deepEqual(r.results.map(p=>p.points),[140,140]);assert.equal(r.players[0].score,(round+1)*140);view(a);assert.equal(view(a).players[0].score,(round+1)*140);call(a,'next',{round});}assert.equal(view(a).phase,'finished');call(a,'start');assert.equal(view(a).round,0);assert.equal(view(a).players[0].score,0);});
test('Chronomètre serveur, absence à zéro, réponse tardive refusée',()=>{let now=1000;const {a,b,call,view}=setup({now:()=>now,roundMs:100});call(a,'start');call(a,'guess',{round:0,cents:10000});now+=101;assert.throws(()=>call(b,'guess',{round:0,cents:10000}),/terminée/);const s=view(a);assert.equal(s.phase,'reveal');assert.equal(s.results.find(p=>p.name==='Alex').points,0);assert.equal(s.results.find(p=>p.name==='Simon').points,150);});
test('Identité, prix invalides et manche périmée sont rejetés',()=>{const {a,game,call}=setup();assert.throws(()=>game.state(a.code,'wrong'),/Session invalide/);call(a,'start');for(const cents of[-1,NaN,Infinity,1.2,'99',100000001])assert.throws(()=>call(a,'guess',{round:0,cents}),/prix/);assert.throws(()=>call(a,'guess',{round:9,cents:100}),/autre manche/);assert.throws(()=>game.join(a.code,'Late'),/commencée/);});
test('Reconnexion, transfert d’hôte, expiration et salon vide',()=>{let now=1000;const {game,a,b,view,call}=setup({now:()=>now,ttlMs:120000});const original=view(a).me;assert.equal(view(a).me,original);now+=61000;assert.equal(view(b).host,view(b).me);call(b,'leave');assert.equal(view(a).host,original);now+=120001;assert.throws(()=>view(a),/expiré/);const c=game.create('C');game.action(c.code,c.token,'leave');assert.equal(game.rooms.size,0);});
test('Capacité, minimum de joueurs et noms',()=>{const game=new Game(products);assert.throws(()=>game.create('  '));const a=game.create('A');assert.throws(()=>game.action(a.code,a.token,'start'),/deux joueurs/);assert.throws(()=>game.join(a.code,'a'),/déjà pris/);for(let i=0;i<7;i++)game.join(a.code,'N'+i);assert.throws(()=>game.join(a.code,'Nine'),/complet/);});
test('Un joueur parti ne reçoit pas le bonus des joueurs restants',()=>{const {a,b,game,call,view}=setup();const c=game.join(a.code,'C');call(a,'start');call(c,'guess',{round:0,cents:10000});call(c,'leave');call(a,'guess',{round:0,cents:9000});call(b,'guess',{round:0,cents:8000});assert.equal(view(a).results.find(x=>x.name==='Simon').bonus,50);});
test('HTTP : deux navigateurs, round trip, fichiers privés inaccessibles',async()=>{const server=createServer(new Game(products));await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;const req=async(path,data,token)=>{const r=await fetch(base+path,{method:data?'POST':'GET',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(data?{body:JSON.stringify(data)}:{})});return{status:r.status,data:await r.json()};};try{assert.equal((await fetch(base+'/')).status,200);for(const path of['/data/products.json','/game.js','/.git/config'])assert.equal((await fetch(base+path)).status,404);const a=(await req('/api/create',{name:'Host'})).data;const b=(await req('/api/join',{name:'Guest',code:a.code})).data;const root='/api/rooms/'+a.code;assert.equal((await req(root)).status,401);assert.equal((await req(root+'/start',{},b.token)).status,403);assert.equal((await req(root+'/start',{},a.token)).data.phase,'guess');await req(root+'/guess',{round:0,cents:10000},a.token);const hidden=(await req(root,null,b.token)).data;assert.equal(hidden.priceCents,undefined);assert.equal(hidden.myGuess,null);const reveal=(await req(root+'/guess',{round:0,cents:5000},b.token)).data;assert.equal(reveal.phase,'reveal');assert.equal(reveal.results[0].points,150);assert.equal((await req(root+'/next',{round:0},a.token)).data.round,1);assert.equal((await req(root+'/next',{round:0},a.token)).status,400);}finally{await new Promise(r=>server.close(r));}});
